---
- include_tasks: configure.yml
  when: ansible_os_family == 'RedHat'

- name: Docker | Install Docker 
  package:
    name: "{{ docker_package }}"
    state: "{{ docker_package_state }}"
    allow_downgrade: true
  notify: restart docker
  ignore_errors: "{{ ansible_check_mode }}"
  when: "ansible_version.full is version_compare('2.12', '>=')"

- name: Docker | Ensure /etc/docker/ directory exists.
  file:
    path: /etc/docker
    state: directory
    mode: 0755
  when: docker_daemon_options.keys() | length > 0

- name: Docker | Configure Docker daemon options.
  copy:
    content: "{{ docker_daemon_options | to_nice_json }}"
    dest: /etc/docker/daemon.json
    mode: 0644
  when: docker_daemon_options.keys() | length > 0
  notify: restart docker

- name: Docker | Ensure Docker is started and enabled at boot.
  service:
    name: docker
    state: "{{ docker_service_state }}"
    enabled: "{{ docker_service_enabled }}"
  ignore_errors: "{{ ansible_check_mode }}"

- name: Docker | Ensure handlers are notified now to avoid firewall conflicts.
  meta: flush_handlers

- include_tasks: users.yml
  when: docker_users | length > 0